---
image:
  tag: v1.5.0	

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: 'ip'
  hosts:
    - server.test.test
  path: /pypiserver
  pathType: ImplementationSpecific

auth:
  existingSecret: ${basic_auth_secret_name}
